name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install -g yarn && yarn install --frozen-lockfile
      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps
      - name: Build server
        run: yarn build
        env:
          CI: true
          NODE_ENV: test
          JWT_TOKEN: "cats are cool"
          COOKIE_NAME: "__qid__"
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - name: Start server and run tests
        run: |
          yarn start &
          yarn wait-on http://localhost:3000
          yarn playwright test
        env:
          CI: true
          NODE_ENV: test
          JWT_TOKEN: "cats are cool"
          COOKIE_NAME: "__qid__"
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
