name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.9

      - name: Update Ubuntu Packages
        run: |
          sudo apt update
          sudo apt upgrade -y

      - name: Install Dependencies
        run: npm install -g yarn && yarn install --frozen-lockfile

      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps

      - name: Build server
        run: yarn build
        env:
          CI: true
          NODE_ENV: test
          JWT_TOKEN: "cats are cool"
          COOKIE_NAME: "__qid__"
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Start server and run tests
        run: |
          yarn start &
          sleep 15
          npx playwright install
          npx playwright test
        env:
          CI: true
          NODE_ENV: test
          JWT_TOKEN: "cats are cool"
          COOKIE_NAME: "__qid__"
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
