name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Build server
        run: yarn build
        env:
          CI: true
          NODE_ENV: test
          JWT_TOKEN: "cats are cool"
          COOKIE_NAME: "__qid__"
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Start server
        run: yarn start > server.log 2>&1 &
        env:
          CI: true
          NODE_ENV: test
          JWT_TOKEN: "cats are cool"
          COOKIE_NAME: "__qid__"
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Print server log
        run: cat server.log

      - name: Run Playwright tests
        run: npx playwright test
        env:
          CI: true
          NODE_ENV: test
          JWT_TOKEN: "cats are cool"
          COOKIE_NAME: "__qid__"
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
